server:
  port: 8761

eureka:
  client:

#    eureka server? eureka server?? ???? ??? ??? ??
    register-with-eureka: false
#    Eureka server? ?? microservice?? ?????(30???) ???? ??? ??? ??.
    fetch-registry: false